services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: campus-trade-oracle
    environment:
      ORACLE_PASSWORD: CampusTrade123!
      APP_USER: CAMPUS_TRADE_USER
      APP_USER_PASSWORD: CampusTrade123!
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./Database/init-oracle.sql:/container-entrypoint-initdb.d/01-init-oracle.sql
      - ./Database/add-students.sql:/container-entrypoint-initdb.d/02-add-students.sql

  campus-trade-api:
    build:
      context: ./Backend/CampusTradeSystem
      dockerfile: CampusTrade.API/Dockerfile
    container_name: campus-trade-api
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=oracle-db:1521/XEPDB1;User Id=CAMPUS_TRADE_USER;Password=CampusTrade123!;
    volumes:
      - ./Storage:/Storage
      - ./logs:/app/logs
    restart: unless-stopped

  campus-trade-web:
    build:
      context: ./Frontend/campus-trade-web
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://8.222.141.205:8080
    container_name: campus-trade-web
    ports:
      - "80:80"
    depends_on:
      - campus-trade-api
    restart: unless-stopped

volumes:
  oracle_data:
